# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2331570596deb9e0c1fad81fd3604c79a7d75a8aae18c37469b281121041ade5f923dd16241e50051d4b8bcd164d2683ed2b71ecc4db5df53fe842431921bb40

test:
  secret_key_base: f8eec44bc0cb206570118dc1be423c52485b176636afa34cdeb2b82a9e88adfd8bfea49e61c61527affb816f9180d0c3daa5fe76f0ce3a4c3b8f803d0ddf521b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
